#cloud-config
# hostname: server
# fqdn: server.local
manage_etc_hosts: true

packages:
  - nginx

users:
  - name: serveradmin
    gecos: System Administrator
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    lock_passwd: false
    shell: /bin/bash    
    
runcmd:
  # Habilitar y arrancar nginx y mariadb
  - systemctl enable nginx
  - systemctl start nginx

  # Modificar la página inicial de nginx para que muestre el nombre del host
  - |
    echo "<html><body><h1>Nombre de host: $(hostname)</h1></body></html>" > /var/www/html/index.nginx-debian.html
