#cloud-config
hostname: ADMIN
fqdn: ADMIN.local
manage_etc_hosts: true

users:
  - name: systemadmin
    gecos: System Administrator
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    lock_passwd: false
    shell: /bin/bash    
    
runcmd:
  # Modificar puerto SSH
  - sudo echo "Port 2022" >> /etc/ssh/sshd_config
  - sudo systemctl restart sshd
  - sudo echo "This is the admin" > /admin.txt
